version: "3.1"
services:

    mysql:
      build:
        context: ./docker/mysql
      container_name: usr-mysql
      command: --init-file /data/application/init.sql
      volumes:
        - ./docker/mysql/init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8090:80

    rabbitmq:
      build:
        context: ./docker/rabbitmq
        args:
          RABBITMQ_USER_ARG: ${RABBITMQ_USER}
          RABBITMQ_PASSWORD_ARG: ${RABBITMQ_PASSWORD}
          RABBITMQ_VHOST_ARG: ${RABBITMQ_VHOST}
          RABBITMQ_CREATE_EXCHANGE_ARG: ${RABBITMQ_CREATE_EXCHANGE}
          RABBITMQ_CREATE_QUEUE_ARG: ${RABBITMQ_CREATE_QUEUE}
          RABBITMQ_INDEX_EXCHANGE_ARG: ${RABBITMQ_INDEX_EXCHANGE}
          RABBITMQ_INDEX_QUEUE_ARG: ${RABBITMQ_INDEX_QUEUE}
      container_name: usr-rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKDFODSQADLRPCDLNMAAEQG"
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      ports:
        - "${RABBITMQ_MGMT_HOST_PORT}:${RABBITMQ_MGMT_CONTAINER_PORT}"
        - "${RABBITMQ_HOST_PORT}:${RABBITMQ_CONTAINER_PORT}"

    manticoresearch:
      image: manticoresearch/manticore
      container_name: usr-manticoresearch
      volumes:
        - ./docker/manticore/sphinx.conf:/etc/sphinxsearch/sphinx.conf
        - /data
      ports:
        - "${SEARCH_HOST_PORT}:${SEARCH_CONTAINER_PORT}"

    webserver:
      image: nginx:alpine
      container_name: usr-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: usr-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASSWORD}
        RABBITMQ_VHOST: ${RABBITMQ_VHOST}
        RABBITMQ_CREATE_EXCHANGE: ${RABBITMQ_CREATE_EXCHANGE}
        RABBITMQ_CREATE_QUEUE: ${RABBITMQ_CREATE_QUEUE}
        RABBITMQ_INDEX_EXCHANGE: ${RABBITMQ_INDEX_EXCHANGE}
        RABBITMQ_INDEX_QUEUE: ${RABBITMQ_INDEX_QUEUE}
        RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${RABBITMQ_CONTAINER_PORT}/${RABBITMQ_VHOST}
        SEARCH_DSN: mysql:host=manticoresearch;port=${SEARCH_CONTAINER_PORT}
        SEARCH_USERS_INDEX: usersrt
