version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: usr-mysql
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"

    rabbitmq:
      build:
        context: ./docker/rabbitmq
        args:
          RABBITMQ_USER_ARG: ${RABBITMQ_USER}
          RABBITMQ_PASSWORD_ARG: ${RABBITMQ_PASSWORD}
          RABBITMQ_VHOST_ARG: ${RABBITMQ_VHOST}
          RABBITMQ_CREATE_EXCHANGE_ARG: ${RABBITMQ_CREATE_EXCHANGE}
          RABBITMQ_CREATE_QUEUE_ARG: ${RABBITMQ_CREATE_QUEUE}
          RABBITMQ_INDEX_EXCHANGE_ARG: ${RABBITMQ_INDEX_EXCHANGE}
          RABBITMQ_INDEX_QUEUE_ARG: ${RABBITMQ_INDEX_QUEUE}
      container_name: usr-rabbitmq
#      volumes:
#        - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKDFODSQADLRPCDLNMAAEQG"
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      ports:
        - "${RABBITMQ_MGMT_HOST_PORT}:${RABBITMQ_MGMT_CONTAINER_PORT}"
        - "${RABBITMQ_HOST_PORT}:${RABBITMQ_CONTAINER_PORT}"

    manticoresearch:
      image: manticoresearch/manticore
      container_name: usr-manticoresearch
      volumes:
        - ./docker/manticore/sphinx.conf:/etc/sphinxsearch/sphinx.conf
        - /data
      ports:
        - "9306:9306"
        - "9312:9312"

    webserver:
      image: nginx:alpine
      container_name: usr-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: usr-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASSWORD}
        RABBITMQ_VHOST: ${RABBITMQ_VHOST}
        RABBITMQ_CREATE_EXCHANGE: ${RABBITMQ_CREATE_EXCHANGE}
        RABBITMQ_CREATE_QUEUE: ${RABBITMQ_CREATE_QUEUE}
        RABBITMQ_INDEX_EXCHANGE: ${RABBITMQ_INDEX_EXCHANGE}
        RABBITMQ_INDEX_QUEUE: ${RABBITMQ_INDEX_QUEUE}
        RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${RABBITMQ_CONTAINER_PORT}
