index:
    path: /
    controller: App\Controller\DefaultController::index
api_users_create:
    path: /api/users
    controller: App\Controller\ApiController::users_create
    methods: POST
api_users_get:
    path: /api/users
    controller: App\Controller\ApiController::users_get
    methods: GET
users_list:
    path: /users
    controller: App\Controller\UsersController::index
users_search:
    path: /users/search
    controller: App\Controller\UsersController::search
